/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAndamentoRouteImport } from './routes/_authenticated/andamento'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedAtendimentoIdRouteImport } from './routes/_authenticated/atendimento.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAndamentoRoute = AuthenticatedAndamentoRouteImport.update({
  id: '/andamento',
  path: '/andamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendimentoIdRoute =
  AuthenticatedAtendimentoIdRouteImport.update({
    id: '/atendimento/$id',
    path: '/atendimento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/andamento': typeof AuthenticatedAndamentoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/atendimento/$id': typeof AuthenticatedAtendimentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/andamento': typeof AuthenticatedAndamentoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/atendimento/$id': typeof AuthenticatedAtendimentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/andamento': typeof AuthenticatedAndamentoRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/nova': typeof AuthenticatedNovaRoute
  '/_authenticated/atendimento/$id': typeof AuthenticatedAtendimentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/andamento'
    | '/buscar'
    | '/historico'
    | '/inicio'
    | '/nova'
    | '/atendimento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/andamento'
    | '/buscar'
    | '/historico'
    | '/inicio'
    | '/nova'
    | '/atendimento/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/andamento'
    | '/_authenticated/buscar'
    | '/_authenticated/historico'
    | '/_authenticated/inicio'
    | '/_authenticated/nova'
    | '/_authenticated/atendimento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/andamento': {
      id: '/_authenticated/andamento'
      path: '/andamento'
      fullPath: '/andamento'
      preLoaderRoute: typeof AuthenticatedAndamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimento/$id': {
      id: '/_authenticated/atendimento/$id'
      path: '/atendimento/$id'
      fullPath: '/atendimento/$id'
      preLoaderRoute: typeof AuthenticatedAtendimentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAndamentoRoute: typeof AuthenticatedAndamentoRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRoute
  AuthenticatedAtendimentoIdRoute: typeof AuthenticatedAtendimentoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAndamentoRoute: AuthenticatedAndamentoRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNovaRoute: AuthenticatedNovaRoute,
  AuthenticatedAtendimentoIdRoute: AuthenticatedAtendimentoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
